export const areaNames = {
    相模湾海底: "Sagami Bay Region",
    北海道地方: "Hokkaido Region",
    東北地方: "Tohoku Region",
    北陸地方: "Hokuriku Region",
    関東甲信地方: "Kanto Region",
    小笠原地方: "Ogasawara Region",
    東海地方: "Tokai Region",
    近畿地方: "Kinki Region",
    中国地方: "Chugoku Region",
    四国地方: "Shikoku Region",
    九州地方: "Kyushu Region",
    沖縄地方: "Okinawa Region",
    石狩地方北部: "Hokkaido Northern Part of Ishikari",
    石狩地方中部: "Hokkaido Central Part of Ishikari",
    石狩地方南部: "Hokkaido Southern Part of Ishikari",
    渡島地方北部: "Hokkaido Northern Part of Oshima",
    渡島地方東部: "Hokkaido Eastern Part of Watashima",
    渡島地方西部: "Hokkaido Western Part of Oshima",
    檜山地方: "Hokkaido Hiyama Region",
    後志地方北部: "Hokkaido Northern Shiribeshi",
    後志地方東部: "Hokkaido Eastern Shiribeshi",
    後志地方西部: "Hokkaido Western Shiribeshi",
    北海道奥尻島: "Hokkaido Okushiri Island Region",
    空知地方北部: "Hokkaido Northern Part of Sorachi",
    空知地方中部: "Hokkaido Central Part of Sorachi",
    空知地方南部: "Hokkaido Southern Part of Sorachi",
    上川地方北部: "Hokkaido Northern Part of Kamikawa",
    上川地方中部: "Hokkaido Central Part of Kamikawa",
    上川地方南部: "Hokkaido Southern Part of Kamikawa",
    留萌地方中北部: "Hokkaido Northern-Central Rumoi",
    留萌地方南部: "Hokkaido Southern Part of Rumoi",
    宗谷地方北部: "Hokkaido Northern Part of Soya",
    宗谷地方南部: "Hokkaido Southern Part of Soya",
    北海道利尻礼文: "Hokkaido Rishiri Ribun Island",
    網走地方: "Hokkaido Abashiri Region",
    北見地方: "Hokkaido Kitami Region",
    紋別地方: "Hokkaido Mombetsu Region",
    胆振地方西部: "Hokkaido Western Part of Iburi",
    胆振地方中東部: "Hokkaido Central Eastern Iburi",
    日高地方西部: "Hokkaido Western Part of Hidaka",
    日高地方中部: "Hokkaido Central Part of Hidaka",
    日高地方東部: "Hokkaido Eastern Part of Hidaka",
    十勝地方北部: "Hokkaido Northern Part of Tokachi",
    十勝地方中部: "Hokkaido Central Part of Tokachi",
    十勝地方南部: "Hokkaido Southern Part of Tokachi",
    釧路地方北部: "Hokkaido Northern Part of Kushiro",
    釧路地方中南部: "Hokkaido Southern Central Kushiro",
    根室地方北部: "Hokkaido Northern Part of Nemuro",
    根室地方中部: "Hokkaido Central Part of Nemuro",
    根室地方南部: "Hokkaido Southern Part of Nemuro",
    北海道南西沖: "Off South-West of Hokkaido",
    北海道西方沖: "Off West of Hokkaido",
    石狩湾: "Ishikari Bay Region",
    北海道北西沖: "Off North-West of Hokkaido",
    宗谷海峡: "Sōya Strait Region",
    国後島付近: "Near Kunashiri Island",
    択捉島付近: "Near Etorofu Island",
    北海道東方沖: "Off Hokkaido Toho",
    根室半島南東沖: "Off SE of Nemuro Peninsula",
    釧路沖: "Off Kushiro",
    十勝沖: "Off Tokachi",
    浦河沖: "Off Urakawa",
    苫小牧沖: "Off Tomakomai",
    内浦湾: "Uchiura Bay Region",
    宗谷東方沖: "Off Soya",
    網走沖: "Off Abashiri",
    択捉島南東沖: "Off South-East of Etorofu Island",
    青森県津軽北部: "Aomori Pref. Northern Tsugaru",
    青森県津軽南部: "Aomori Pref. Southern Tsugaru",
    青森県三八上北地方: "Aomori Pref. Sampachi-Kamikita",
    青森県下北地方: "Aomori Pref. Shimokita Region",
    岩手県沿岸北部: "North Coastal Region of Iwate Pref.",
    岩手県沿岸南部: "South Coastal Region of Iwate Pref.",
    岩手県内陸北部: "North Inland Region of Iwate Pref.",
    岩手県内陸南部: "South Inland Region of Iwate Pref.",
    宮城県北部: "Northern Part of Miyagi Pref.",
    宮城県南部: "Southern Part of Miyagi Pref.",
    宮城県中部: "Central Part of Miyagi Pref.",
    秋田県沿岸北部: "North Coastal Region of Akita Pref.",
    秋田県沿岸南部: "South Coastal Region of Akita Pref.",
    秋田県内陸北部: "North Inland Region of Akita Pref.",
    秋田県内陸南部: "South Inland Region of Akita Pref.",
    山形県庄内地方: "Yamagata Pref. Shonai Region",
    山形県最上地方: "Yamagata Pref. Mogami Region",
    山形県村山地方: "Yamagata Pref. Murayama Region",
    山形県置賜地方: "Yamagata Pref. Yamagata Region",
    福島県中通り: "Fukushima Pref. Nakadoori Region",
    福島県浜通り: "Fukushima Pref. Hamadoori Region",
    福島県会津: "Fukushima Pref. Aizu Region",
    津軽海峡: "Tsugaru Strait Region",
    山形県沖: "Off Yamagata Prefecture",
    秋田県沖: "Off Akita Prefecture",
    青森県西方沖: "Off West of Aomori Pref.",
    陸奥湾: "Mutsu Bay Region",
    青森県東方沖: "Off Aomori Prefecture",
    岩手県沖: "Off Iwate Prefecture",
    宮城県沖: "Off Miyagi Prefecture",
    三陸沖: "Off Sanriku",
    福島県沖: "Off Fukushima Prefecture",
    茨城県北部: "Northern Part of Ibaraki Pref.",
    茨城県南部: "Southern Part of Ibaraki Pref.",
    千葉県南東沖: "Off SE of Chiba Pref.",
    栃木県北部: "Northern Part of Tochigi Pref.",
    栃木県南部: "Southern Part of Tochigi Pref.",
    群馬県北部: "Northern Part of Gumma Pref.",
    群馬県南部: "Southern Part of Gunma Pref.",
    埼玉県北部: "Northern Part of Saitama Pref.",
    埼玉県南部: "Southern Part of Saitama Pref.",
    埼玉県秩父地方: "Saitama Pref. Chichibu Region",
    千葉県北東部: "North-Eastern Part of Chiba Pref.",
    千葉県北西部: "North-Western Part of Chiba Pref.",
    千葉県南部: "Southern Part of Chiba Pref.",
    房総半島南方沖: "Off Boso Peninsula",
    東京都２３区: "The 23 Wards of Tokyo",
    東京都多摩東部: "Tokyo Pref. Eastern Tama Region",
    東京都多摩西部: "Tokyo Pref. Western Tama Region",
    神津島: "Kozushima Island Region",
    伊豆大島: "Izu Oshima Island Region",
    新島: "Niijima Island Region",
    三宅島: "Miyakejima Island Region",
    八丈島: "Hachijojima Island Region",
    小笠原: "Ogasawara Island Region",
    神奈川県東部: "Eastern Part of Kanagawa Pref.",
    神奈川県西部: "Western Part of Kanagawa Pref.",
    新潟県上越地方: "Niigata Pref. Joetsu Region",
    新潟県中越地方: "Niigata Pref. Chuetsu Region",
    新潟県下越地方: "Niigata Pref. Kaetsu Region",
    新潟県佐渡: "Niigata Pref. Sado Island Region",
    新潟県下越沖: "Off Niigata Pref. Kaetsu",
    新潟県上中越沖: "Off Niigata Pref. Chuetsu",
    富山県東部: "Eastern Part of Toyama Pref.",
    富山県西部: "Western Part of Toyama Pref.",
    石川県能登地方: "Ishikawa Pref. Noto Region",
    石川県加賀地方: "Ishikawa Pref. Kaga Region",
    福井県嶺北: "Fukui Pref. Reihoku Region",
    福井県嶺南: "Fukui Pref. Reinan Region",
    "山梨県中・西部": "Western-Central Yamanashi Pref",
    "山梨県東部・富士五湖": "Eastern Yamanashi Pref Fujigoko",
    長野県北部: "Northern Part of Nagano Pref.",
    長野県中部: "Central Part of Nagano Pref.",
    長野県南部: "Southern Part of Nagano Pref.",
    岐阜県飛騨地方: "Gifu Pref. Hida Region",
    岐阜県美濃東部: "Gifu Pref. Eastern Part of Mino",
    岐阜県美濃中西部: "Gifu Pref. Western-Central Mino",
    静岡県伊豆地方: "Shizuoka Pref. Izu Region",
    静岡県東部: "Eastern Part of Shizuoka Pref.",
    静岡県中部: "Central Part of Shizuoka Pref.",
    静岡県西部: "Western Part of Shizuoka Pref.",
    愛知県東部: "Eastern Part of Aichi Pref.",
    愛知県西部: "Western Part of Aichi Pref.",
    三重県北部: "Northern Part of Mie Pref.",
    三重県中部: "Central Part of Mie Pref.",
    三重県南部: "Southern Part of Mie Pref.",
    三重県南東沖: "Off SE of Mie Pref.",
    茨城県沖: "Off Ibaraki Prefecture",
    関東東方沖: "Off East of Kanto",
    千葉県東方沖: "Off East of Chiba Pref.",
    八丈島東方沖: "Off E of Hachijojima Island",
    八丈島近海: "Sea near Hachijojima Island",
    東京湾: "Tokyo Bay Region",
    相模湾: "Sagami Bay Region",
    伊豆大島近海: "Near Izu-Oshima Island",
    伊豆半島東方沖: "Off East of Izu Peninsula",
    三宅島近海: "Sea near Miyakejima Island",
    "新島・神津島近海": "Sea near Niijima / Kozu Island",
    駿河湾: "Suruga Bay Region",
    駿河湾南方沖: "Off S of Suruga Bay",
    遠州灘: "Enshu-nada Sea Region",
    三河湾: "Mikawa Bay Region",
    伊勢湾: "Ise Bay Region",
    若狭湾: "Wakasa Bay Region",
    福井県沖: "Off Fukui Prefecture",
    石川県西方沖: "Off West of Ishikawa Pref.",
    能登半島沖: "Off Noto Peninsula",
    富山湾: "Toyama Bay Region",
    佐渡付近: "Near Sado Island",
    東海道南方沖: "Off South of Tokai District",
    滋賀県北部: "Northern Part of Shiga Pref.",
    滋賀県南部: "Southern Part of Shiga Pref.",
    京都府北部: "Northern Part of Kyoto Pref.",
    京都府南部: "Southern Part of Kyoto Pref.",
    大阪府北部: "Northern Part of Osaka Pref.",
    大阪府南部: "Southern Part of Osaka Pref.",
    兵庫県北部: "Northern Part of Hyogo Pref.",
    兵庫県南東部: "South-Eastern Part of Hyogo Pref.",
    兵庫県南西部: "South-Western Part of Hyogo Pref.",
    兵庫県淡路島: "Hyogo Pref. Awaji Island Region",
    奈良県: "Nara Pref.",
    和歌山県北部: "Northern Part of Wakayama Pref.",
    和歌山県南部: "Southern Part of Wakayama Pref.",
    鳥取県東部: "Eastern Part of Tottori Pref.",
    鳥取県中部: "Central Part of Tottori Pref.",
    鳥取県西部: "Western Part of Tottori Pref.",
    島根県東部: "Eastern Part of Shimane Pref.",
    島根県西部: "Western Part of Shimane Pref.",
    島根県隠岐: "Shimane Pref. Oki Islands Region",
    岡山県北部: "Northern Part of Okayama Pref.",
    岡山県南部: "Southern Part of Okayama Pref.",
    広島県北部: "Northern Part of Hiroshima Pref.",
    広島県南東部: "South-Eastern Hiroshima Pref.",
    広島県南西部: "South-Western Hiroshima Pref.",
    徳島県北部: "Northern Part of Tokushima Pref.",
    徳島県南部: "Southern Part of Tokushima Pref.",
    香川県東部: "Eastern Part of Kagawa Pref.",
    香川県西部: "Western Part of  Kagawa Pref.",
    愛媛県東予: "Ehime Pref. Toyo Region",
    愛媛県中予: "Ehime Pref. Chuyo Region",
    愛媛県南予: "Ehime Pref. Nanyo Region",
    高知県東部: "Eastern Part of Kochi Pref.",
    高知県中部: "Central Part of Kochi Pref.",
    高知県西部: "Western Part of Kochi Pref.",
    土佐湾: "Tosa Bay Region",
    紀伊水道: "Kii Channel Region",
    大阪湾: "Osaka Bay Region",
    播磨灘: "Harima-nada Sea",
    瀬戸内海中部: "Central Setonaikai",
    安芸灘: "Aki-nada Sea",
    周防灘: "Suo-nada Sea",
    伊予灘: "Iyo-nada Sea",
    豊後水道: "Bungo Channel",
    山口県北西沖: "Off NE of Yamaguchi Pref.",
    島根県沖: "Off Shimane Prefecture",
    鳥取県沖: "Off Tottori Prefecture",
    隠岐島近海: "Seas near Oki Islands Region",
    兵庫県北方沖: "Off North-West of Hyogo Pref.",
    京都府沖: "Off Kyoto Prefecture",
    淡路島付近: "Sea Near Awajishima Island",
    和歌山県南方沖: "Off South of Wakayama Pref.",
    山口県北部: "Northern Part of Yamaguchi Pref.",
    山口県西部: "Western  Part of Yamaguchi Pref.",
    山口県東部: "Eastern Part of Yamaguchi Pref.",
    山口県中部: "Central Part of Yamaguchi Pref.",
    福岡県福岡地方: "Fukuoka Pref. Fukuoka Region",
    福岡県北九州地方: "Fukuoka Pref. Kitakyushu Region",
    福岡県筑豊地方: "Fukuoka Pref. Chikuho Region",
    福岡県筑後地方: "Fukuoka Pref. Chikugo Region",
    佐賀県北部: "Northern Part of Saga Pref.",
    佐賀県南部: "Southern Part of Saga Pref.",
    長崎県北部: "Northern Part of Nagasaki Pref.",
    長崎県南西部: "SW Part of Nagasaki Pref.",
    長崎県島原半島: "Nagasaki Pref. Shimabara Peninsula",
    長崎県対馬: "Nagasaki Pref. Tsushima Island",
    長崎県壱岐: "Nagasaki Pref. Iki Island Region",
    長崎県五島: "Nagasaki Pref. Goto Islands Region",
    熊本県阿蘇地方: "Kumamoto Pref Aso Region",
    熊本県熊本地方: "Kumamoto Pref Kumamoto Region",
    熊本県球磨地方: "Kumamoto Pref Kuma Region",
    "熊本県天草・芦北地方": "Kumamoto Pref Amakusa/Ashikita",
    大分県北部: "Northern Part of Oita Pref.",
    大分県中部: "Central Part of Oita Pref.",
    大分県南部: "Southern Part of Oita Pref.",
    大分県西部: "Western Part of Oita Pref.",
    宮崎県北部平野部: "Miyazaki Pref Northern Heiyabu",
    宮崎県北部山沿い: "Miyazaki Pref Northern Yamazoi",
    宮崎県南部平野部: "Miyazaki Pref Southern Heiyabu",
    宮崎県南部山沿い: "Miyazaki Pref Southern Yamazoi",
    鹿児島県薩摩地方: "Kagoshima Pref. Satsuma Region",
    鹿児島県大隅地方: "Kagoshima Pref. Osumi Region",
    鹿児島県十島村: "Kagoshima Toshima Islands Region",
    鹿児島県甑島: "Kagoshima Koshikijima Islands",
    鹿児島県種子島: "Kagoshima Tanegashima Islands",
    鹿児島県屋久島: "Kagoshima Yakushima Islands Region",
    鹿児島県奄美北部: "Kagoshima Northern Part of Amami",
    鹿児島県奄美南部: "Kagoshima Southern Part of Amami",
    五島列島近海: "Seas near Goto Islands",
    天草灘: "Amakusa-Nada Sea",
    有明海: "Ariake Sea",
    橘湾: "Tachibana Bay Region",
    鹿児島湾: "Kagoshima Bay Region",
    種子島近海: "Seas near Tanegashima",
    日向灘: "Hyuga-nada Sea",
    奄美大島近海: "Seas near Amami Island",
    "壱岐・対馬近海": "Seas near Iki and Tsushima Islands",
    福岡県北西沖: "Off North-West of Fukuoka Pref.",
    薩摩半島西方沖: "Off W of Satsuma Peninsula",
    トカラ列島近海: "Seas near Tokara Islands",
    奄美大島北西沖: "Off North-West of Amami Island",
    沖縄県本島北部: "N Part of Okinawa Main Island",
    沖縄県本島中南部: "S-Central Okinawa Main Island",
    沖縄県久米島: "Okinawa Kumejima Island Region",
    沖縄県宮古島: "Okinawa Miyakojima Island Region",
    沖縄県石垣島: "Okinawa Ishigakijima Island Region",
    沖縄県西表島: "Okinawa Iriomotejima Island Region",
    大隅半島東方沖: "Off E of the Osumi Peninsula",
    九州地方南東沖: "Off South-East of Kyushu",
    種子島南東沖: "Off Tanegashima",
    奄美大島北東沖: "Off North-East of Amami Island",
    沖縄本島近海: "Seas near Okinawa Main Island",
    南大東島近海: "Sea near Southern Daito Islands",
    沖縄本島南方沖: "Offshore of Okinawa Main Island",
    宮古島近海: "Sea near Miyakojima Island",
    石垣島近海: "Sea near Ishigakijima  Island",
    石垣島南方沖: "Off S of Ishigakijima Island",
    西表島付近: "Sea near Iriomote Island",
    与那国島近海: "Sea near Yonagunijima Island",
    沖縄本島北西沖: "Off NW of Okinawa Main Island",
    宮古島北西沖: "Off NW of Miyakojima",
    石垣島北西沖: "Off NW of Ishigakijima",
    台湾付近: "Near the coast of Taiwan",
    東シナ海: "Eastern Chinese Sea",
    四国沖: "Off Shikoku",
    鳥島近海: "Seas near Torishima Island",
    鳥島東方沖: "Off Torishima",
    オホーツク海南部: "South of the coast of Okhotsk",
    サハリン西方沖: "Off the west coast of Sakhalin",
    日本海北部: "Northern Sea of Japan",
    日本海中部: "Central Sea of Japan",
    日本海西部: "Western Sea of Japan",
    父島近海: "Sea near Chichijima Island",
    千島列島: "Kuril Islands Region",
    千島列島南東沖: "Off SE of Kuril Islands",
    北海道南東沖: "Off South-East of Hokkaido",
    東北地方東方沖: "Off East of Tohoku",
    小笠原諸島西方沖: "Off W of Ogasawara Islands",
    硫黄島近海: "Seas near Iwo Jima Islands",
    小笠原諸島東方沖: "Off E of Ogasawara Islands",
    南海道南方沖: "Off South of Nankai Region",
    薩南諸島東方沖: "Off E of Satsunan Islands",
    本州南方沖: "Off South-East of Honshu",
    サハリン南部付近: "Seas near Southern Sakhalin",
    北西太平洋: "North-Western Pacific Ocean",
    マリアナ諸島: "Mariana Islands Region",
    黄海: "Yellow Sea",
    朝鮮半島南部: "Southern Part of Korean Peninsula",
    朝鮮半島北部: "Northern Part of Korean Peninsula",
    中国東北部: "North-Eastern Part of China",
    ウラジオストク付近: "Near Vladivostok",
    シベリア南部: "Southern Siberia",
    サハリン近海: "Sea of Sakhalin",
    アリューシャン列島: "Aleutin Islands Region",
    カムチャツカ半島付近: "Near Kamchatka Peninsula",
    北米西部: "Western Part of North America",
    北米中部: "Central Part of North America",
    北米東部: "Eastern Part of North America",
    中米: "Central America",
    南米西部: "Western Part of South America",
    南米中部: "Central Part of South America",
    南米東部: "Eastern Part of South America",
    北東太平洋: "North-Eastern Pacific Ocean",
    南太平洋: "Southern Pacific Ocean",
    インドシナ半島付近: "Near the Indochinese Peninsula",
    フィリピン付近: "Near the Philippines",
    インドネシア付近: "Near Indonesia",
    グアム付近: "Near Guam",
    ニューギニア付近: "Near New Guinea",
    ニュージーランド付近: "Near New Zealand",
    オーストラリア付近: "Near Australia",
    シベリア付近: "Near Siberia",
    ロシア西部: "Western Part of Russia",
    ロシア中部: "Central Part of Russia",
    ロシア東部: "Eastern Part of Russia",
    中央アジア: "Central Part of Asia",
    中国西部: "Western Part of China",
    中国中部: "Central Part of China",
    中国東部: "Eastern Part of China",
    インド付近: "Near India",
    インド洋: "The Indian Ocean",
    中東: "The Middle East",
    ヨーロッパ西部: "Western Part of Europe",
    ヨーロッパ中部: "Central Part of Europe",
    ヨーロッパ東部: "Eastern Part of Europe",
    地中海: "Mediterranean Sea",
    アフリカ西部: "Western Part of Africa",
    アフリカ中部: "Central Part of Africa",
    アフリカ東部: "Eastern Part of Africa",
    北大西洋: "Northern Atlantic Ocean",
    南大西洋: "Southern Atlantic Ocean",
    北極付近: "Near the North Pole",
    南極付近: "Near the South Pole",
    遠地: "Far away"
};
